import { LABELS } from "@hestia/core";

export interface OverrideInput {
  /** Parsed user compose file (the object form). */
  userCompose: unknown;
  project: string;
  repo: string;
  branch: string;
  worktree: string;
  /** Services to isolate; must exist in userCompose.services. */
  services: string[];
}

export interface OverrideResult {
  yaml: string;
  /** service -> container ports we published (first is the canonical `.port`). */
  servicePorts: Record<string, number[]>;
  serviceBindings: Record<string, Array<{ target: number; protocol: "tcp" | "udp" }>>;
}

/** YAML double-quote a scalar. */
function q(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * Pull the container-side port(s) out of a compose `ports:` entry, which may be
 * `"54322:5432"`, `"127.0.0.1:54322:5432"`, `"5432"`, `5432`, or the long form
 * `{ target: 5432, published: 54322 }`.
 */
function containerBindingsOf(portsEntry: unknown): Array<{ target: number; protocol: "tcp" | "udp" }> {
  if (!Array.isArray(portsEntry)) return [];
  const out: Array<{ target: number; protocol: "tcp" | "udp" }> = [];
  for (const p of portsEntry) {
    if (typeof p === "number") {
      out.push({ target: p, protocol: "tcp" });
    } else if (typeof p === "string") {
      const [spec, rawProtocol = "tcp"] = p.split("/");
      const parts = spec.split(":");
      const last = parts[parts.length - 1]!;
      const n = Number.parseInt(last, 10);
      if (Number.isFinite(n) && (rawProtocol === "tcp" || rawProtocol === "udp")) {
        out.push({ target: n, protocol: rawProtocol });
      }
    } else if (p && typeof p === "object" && "target" in p) {
      const n = Number((p as { target: unknown }).target);
      const rawProtocol = (p as { protocol?: unknown }).protocol ?? "tcp";
      if (Number.isFinite(n) && (rawProtocol === "tcp" || rawProtocol === "udp")) {
        out.push({ target: n, protocol: rawProtocol });
      }
    }
  }
  return out;
}

/**
 * Generate the compose override that isolates the selected services:
 *  - `ports: !override` replaces the user's host mappings with ephemeral
 *    loopback publishes (`127.0.0.1:0:<container>`), so Docker assigns a free
 *    host port and nothing collides across worktrees.
 *  - `container_name` is always rewritten (a pinned name collides even under -p).
 *  - `restart: "no"` so Docker never restarts a container behind us and hands
 *    it a *new* ephemeral port our injected env wouldn't know about.
 *  - `dev.hestia.*` labels make every container discoverable for status/gc.
 *
 * Networks and unnamed/named volumes are isolated automatically by `-p`, so the
 * override deliberately touches services only.
 */
export function generateOverride(input: OverrideInput): OverrideResult {
  const { userCompose, project, repo, branch, worktree, services } = input;
  const composeServices =
    (userCompose as { services?: Record<string, unknown> } | null)?.services ??
    {};

  const servicePorts: Record<string, number[]> = {};
  const serviceBindings: Record<string, Array<{ target: number; protocol: "tcp" | "udp" }>> = {};
  const blocks: string[] = [];

  for (const svc of services) {
    const def = composeServices[svc] as { ports?: unknown } | undefined;
    if (def === undefined) {
      throw new Error(
        `service "${svc}" is not defined in the compose file (have: ${Object.keys(
          composeServices,
        ).join(", ") || "none"})`,
      );
    }
    const bindings = containerBindingsOf(def.ports);
    const cports = bindings.map((binding) => binding.target);
    servicePorts[svc] = cports;
    serviceBindings[svc] = bindings;

    const lines: string[] = [];
    lines.push(`  ${q(svc)}:`);
    lines.push(`    container_name: ${q(`hestia-${project}-${svc}`)}`);
    lines.push(`    restart: "no"`);
    if (cports.length > 0) {
      lines.push(`    ports: !override`);
      for (const binding of bindings) {
        lines.push(`      - ${q(`127.0.0.1:0:${binding.target}/${binding.protocol}`)}`);
      }
    }
    lines.push(`    labels:`);
    lines.push(`      ${q(LABELS.stack)}: ${q(project)}`);
    lines.push(`      ${q(LABELS.repo)}: ${q(repo)}`);
    lines.push(`      ${q(LABELS.branch)}: ${q(branch)}`);
    lines.push(`      ${q(LABELS.worktree)}: ${q(worktree)}`);
    blocks.push(lines.join("\n"));
  }

  const yaml = `# generated by hestia — do not edit\nservices:\n${blocks.join(
    "\n",
  )}\n`;
  return { yaml, servicePorts, serviceBindings };
}
